// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc.matchrpc;

public final class AntPathMatch {
  private AntPathMatch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Paths_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Paths_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024antpathmatcher.proto\022\003rpc\"*\n\005Paths\022\017\n\007" +
      "pattern\030\001 \001(\t\022\020\n\010realPath\030\002 \001(\t\"\025\n\006Resul" +
      "t\022\013\n\003res\030\001 \001(\01026\n\016AntPathMatcher\022$\n\005matc" +
      "h\022\n.rpc.Paths\032\013.rpc.Result\"\000(\001B5\n\017com.ky" +
      "riexu.rpcB\014AntPathMatchP\001Z\022gateway/commo" +
      "n/rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_Paths_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_Paths_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Paths_descriptor,
        new String[] { "Pattern", "RealPath", });
    internal_static_rpc_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Result_descriptor,
        new String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
