// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc;

public interface GoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realPath = 1;</code>
   * @return The realPath.
   */
  java.lang.String getRealPath();
  /**
   * <code>string realPath = 1;</code>
   * @return The bytes for realPath.
   */
  com.google.protobuf.ByteString
      getRealPathBytes();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string remoteAddr = 3;</code>
   * @return The remoteAddr.
   */
  java.lang.String getRemoteAddr();
  /**
   * <code>string remoteAddr = 3;</code>
   * @return The bytes for remoteAddr.
   */
  com.google.protobuf.ByteString
      getRemoteAddrBytes();

  /**
   * <code>string proto = 4;</code>
   * @return The proto.
   */
  java.lang.String getProto();
  /**
   * <code>string proto = 4;</code>
   * @return The bytes for proto.
   */
  com.google.protobuf.ByteString
      getProtoBytes();

  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  boolean containsHeader(
      java.lang.String key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.kyriexu.rpc.Header>
  getHeader();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  java.util.Map<java.lang.String, com.kyriexu.rpc.Header>
  getHeaderMap();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */

  com.kyriexu.rpc.Header getHeaderOrDefault(
      java.lang.String key,
      com.kyriexu.rpc.Header defaultValue);
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */

  com.kyriexu.rpc.Header getHeaderOrThrow(
      java.lang.String key);
}
