// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc.matchrpc;

public interface GoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realPath = 1;</code>
   * @return The realPath.
   */
  String getRealPath();
  /**
   * <code>string realPath = 1;</code>
   * @return The bytes for realPath.
   */
  com.google.protobuf.ByteString
      getRealPathBytes();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string remoteAddr = 3;</code>
   * @return The remoteAddr.
   */
  String getRemoteAddr();
  /**
   * <code>string remoteAddr = 3;</code>
   * @return The bytes for remoteAddr.
   */
  com.google.protobuf.ByteString
      getRemoteAddrBytes();

  /**
   * <code>string proto = 4;</code>
   * @return The proto.
   */
  String getProto();
  /**
   * <code>string proto = 4;</code>
   * @return The bytes for proto.
   */
  com.google.protobuf.ByteString
      getProtoBytes();

  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  boolean containsHeader(
      String key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Header>
  getHeader();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */
  java.util.Map<String, Header>
  getHeaderMap();
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */

  Header getHeaderOrDefault(
      String key,
      Header defaultValue);
  /**
   * <code>map&lt;string, .rpc.Header&gt; header = 5;</code>
   */

  Header getHeaderOrThrow(
      String key);
}
