// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @return A list containing the headerValue.
   */
  java.util.List<java.lang.String>
      getHeaderValueList();
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @return The count of headerValue.
   */
  int getHeaderValueCount();
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @param index The index of the element to return.
   * @return The headerValue at the given index.
   */
  java.lang.String getHeaderValue(int index);
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the headerValue at the given index.
   */
  com.google.protobuf.ByteString
      getHeaderValueBytes(int index);
}
