// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc;

/**
 * Protobuf type {@code rpc.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    headerValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Header(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              headerValue_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            headerValue_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        headerValue_ = headerValue_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kyriexu.rpc.AntPathMatch.internal_static_rpc_Header_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kyriexu.rpc.AntPathMatch.internal_static_rpc_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kyriexu.rpc.Header.class, com.kyriexu.rpc.Header.Builder.class);
  }

  public static final int HEADERVALUE_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList headerValue_;
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @return A list containing the headerValue.
   */
  public com.google.protobuf.ProtocolStringList
      getHeaderValueList() {
    return headerValue_;
  }
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @return The count of headerValue.
   */
  public int getHeaderValueCount() {
    return headerValue_.size();
  }
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @param index The index of the element to return.
   * @return The headerValue at the given index.
   */
  public java.lang.String getHeaderValue(int index) {
    return headerValue_.get(index);
  }
  /**
   * <code>repeated string HeaderValue = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the headerValue at the given index.
   */
  public com.google.protobuf.ByteString
      getHeaderValueBytes(int index) {
    return headerValue_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < headerValue_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, headerValue_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < headerValue_.size(); i++) {
        dataSize += computeStringSizeNoTag(headerValue_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getHeaderValueList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kyriexu.rpc.Header)) {
      return super.equals(obj);
    }
    com.kyriexu.rpc.Header other = (com.kyriexu.rpc.Header) obj;

    if (!getHeaderValueList()
        .equals(other.getHeaderValueList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHeaderValueCount() > 0) {
      hash = (37 * hash) + HEADERVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderValueList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kyriexu.rpc.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kyriexu.rpc.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kyriexu.rpc.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kyriexu.rpc.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kyriexu.rpc.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kyriexu.rpc.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kyriexu.rpc.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.Header)
      com.kyriexu.rpc.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kyriexu.rpc.AntPathMatch.internal_static_rpc_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kyriexu.rpc.AntPathMatch.internal_static_rpc_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kyriexu.rpc.Header.class, com.kyriexu.rpc.Header.Builder.class);
    }

    // Construct using com.kyriexu.rpc.Header.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      headerValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kyriexu.rpc.AntPathMatch.internal_static_rpc_Header_descriptor;
    }

    @java.lang.Override
    public com.kyriexu.rpc.Header getDefaultInstanceForType() {
      return com.kyriexu.rpc.Header.getDefaultInstance();
    }

    @java.lang.Override
    public com.kyriexu.rpc.Header build() {
      com.kyriexu.rpc.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kyriexu.rpc.Header buildPartial() {
      com.kyriexu.rpc.Header result = new com.kyriexu.rpc.Header(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        headerValue_ = headerValue_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.headerValue_ = headerValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kyriexu.rpc.Header) {
        return mergeFrom((com.kyriexu.rpc.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kyriexu.rpc.Header other) {
      if (other == com.kyriexu.rpc.Header.getDefaultInstance()) return this;
      if (!other.headerValue_.isEmpty()) {
        if (headerValue_.isEmpty()) {
          headerValue_ = other.headerValue_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureHeaderValueIsMutable();
          headerValue_.addAll(other.headerValue_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kyriexu.rpc.Header parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kyriexu.rpc.Header) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList headerValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureHeaderValueIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        headerValue_ = new com.google.protobuf.LazyStringArrayList(headerValue_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @return A list containing the headerValue.
     */
    public com.google.protobuf.ProtocolStringList
        getHeaderValueList() {
      return headerValue_.getUnmodifiableView();
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @return The count of headerValue.
     */
    public int getHeaderValueCount() {
      return headerValue_.size();
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param index The index of the element to return.
     * @return The headerValue at the given index.
     */
    public java.lang.String getHeaderValue(int index) {
      return headerValue_.get(index);
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the headerValue at the given index.
     */
    public com.google.protobuf.ByteString
        getHeaderValueBytes(int index) {
      return headerValue_.getByteString(index);
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param index The index to set the value at.
     * @param value The headerValue to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderValue(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderValueIsMutable();
      headerValue_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param value The headerValue to add.
     * @return This builder for chaining.
     */
    public Builder addHeaderValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderValueIsMutable();
      headerValue_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param values The headerValue to add.
     * @return This builder for chaining.
     */
    public Builder addAllHeaderValue(
        java.lang.Iterable<java.lang.String> values) {
      ensureHeaderValueIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, headerValue_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeaderValue() {
      headerValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string HeaderValue = 1;</code>
     * @param value The bytes of the headerValue to add.
     * @return This builder for chaining.
     */
    public Builder addHeaderValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureHeaderValueIsMutable();
      headerValue_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.Header)
  }

  // @@protoc_insertion_point(class_scope:rpc.Header)
  private static final com.kyriexu.rpc.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kyriexu.rpc.Header();
  }

  public static com.kyriexu.rpc.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @java.lang.Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Header(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kyriexu.rpc.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

