// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc.matchrpc;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool res = 1;</code>
   * @return The res.
   */
  boolean getRes();
}
