server:
  port: 8080

log:
  level: info

gin:
  mode: debug

session:
  max_age: 20

rpc:
  matcher:
    server_addr: "192.168.127.128:9000"

# 决定 user 中间件是否开启
admin:
  filter: false

proxy:
  http:
    addr: ":8089"
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 20
  https:
    addr: ":8090"
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 20

cluster:
  cluster_ip: "127.0.0.1"
  cluster_port: "8091"
  cluster_ssl_port: "8092"