server:
  port: 8080

log:
  level: info

gin:
  mode: debug

session:
  max_age: 20

rpc:
  matcher:
    server_addr: "localhost:9000"

whitelist:
  - "/**/login"
  - "/**/register"
  - "/**.js"
  - "/**.css"
  - "/**.html"