// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antpathmatcher.proto

package com.kyriexu.rpc;

public interface PathsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Paths)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pattern = 1;</code>
   * @return The pattern.
   */
  String getPattern();
  /**
   * <code>string pattern = 1;</code>
   * @return The bytes for pattern.
   */
  com.google.protobuf.ByteString
      getPatternBytes();

  /**
   * <code>string realPath = 2;</code>
   * @return The realPath.
   */
  String getRealPath();
  /**
   * <code>string realPath = 2;</code>
   * @return The bytes for realPath.
   */
  com.google.protobuf.ByteString
      getRealPathBytes();
}
