// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: rpc/antpathmatcher.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Paths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern  string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	RealPath string `protobuf:"bytes,2,opt,name=realPath,proto3" json:"realPath,omitempty"`
}

func (x *Paths) Reset() {
	*x = Paths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_antpathmatcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paths) ProtoMessage() {}

func (x *Paths) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_antpathmatcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paths.ProtoReflect.Descriptor instead.
func (*Paths) Descriptor() ([]byte, []int) {
	return file_rpc_antpathmatcher_proto_rawDescGZIP(), []int{0}
}

func (x *Paths) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Paths) GetRealPath() string {
	if x != nil {
		return x.RealPath
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_antpathmatcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_antpathmatcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_rpc_antpathmatcher_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_rpc_antpathmatcher_proto protoreflect.FileDescriptor

var file_rpc_antpathmatcher_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x6e, 0x74, 0x70, 0x61, 0x74, 0x68, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22,
	0x3d, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x1a,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x36, 0x0a, 0x0e, 0x41, 0x6e,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x1a, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x28, 0x01, 0x42, 0x35, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x79, 0x72, 0x69, 0x65, 0x78,
	0x75, 0x2e, 0x72, 0x70, 0x63, 0x42, 0x0c, 0x41, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x01, 0x5a, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_antpathmatcher_proto_rawDescOnce sync.Once
	file_rpc_antpathmatcher_proto_rawDescData = file_rpc_antpathmatcher_proto_rawDesc
)

func file_rpc_antpathmatcher_proto_rawDescGZIP() []byte {
	file_rpc_antpathmatcher_proto_rawDescOnce.Do(func() {
		file_rpc_antpathmatcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_antpathmatcher_proto_rawDescData)
	})
	return file_rpc_antpathmatcher_proto_rawDescData
}

var file_rpc_antpathmatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_antpathmatcher_proto_goTypes = []interface{}{
	(*Paths)(nil),  // 0: rpc.Paths
	(*Result)(nil), // 1: rpc.Result
}
var file_rpc_antpathmatcher_proto_depIdxs = []int32{
	0, // 0: rpc.AntPathMatcher.match:input_type -> rpc.Paths
	1, // 1: rpc.AntPathMatcher.match:output_type -> rpc.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_antpathmatcher_proto_init() }
func file_rpc_antpathmatcher_proto_init() {
	if File_rpc_antpathmatcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_antpathmatcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_antpathmatcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_antpathmatcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_antpathmatcher_proto_goTypes,
		DependencyIndexes: file_rpc_antpathmatcher_proto_depIdxs,
		MessageInfos:      file_rpc_antpathmatcher_proto_msgTypes,
	}.Build()
	File_rpc_antpathmatcher_proto = out.File
	file_rpc_antpathmatcher_proto_rawDesc = nil
	file_rpc_antpathmatcher_proto_goTypes = nil
	file_rpc_antpathmatcher_proto_depIdxs = nil
}
